RECORD_DIR = "/mnt/nvme/recordings/"
TMP_DIR = "/mnt/nvme/tmp/"
EVENT_SNAPSHOT_FILE_NAME = "event_snapshot.bmp"
VIDEO_SNAPSHOT_FILE_NAME = "video_snapshot.jpg"
SERIAL_PORT="/dev/ttyUSB0"
PORT = 80
DEBUG = False
VOLT2_GAIN = (10 + 5) / 5
VOLT1_GAIN = (10 + 10) / 10
LOW_CELL_WARN = 3.5
LOW_CELL_POWER_OFF = 3.2
LOW_TOTAL_WARN = 7
LOW_TOTAL_POWER_OFF = 6.4
VERSION="1.1"